[build-system]
requires = [
  "setuptools>=42",
  "setuptools_scm[toml]>=6.3"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
local_scheme = "node-and-date"
root = ".."
